In [62]:
import pandas as pd
pd.options.display.max_columns = 60
pd.options.display.max_rows = 60

In [5]:
bank_data = pd.read_csv("./bank_v1.csv")

In [7]:
bank_data.head()

,age,balance,day,duration,campaign,pdays,previous,id,risk,resp,pdays_missing,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,marital_divorced,marital_married,marital_single,education_primary,education_secondary,education_tertiary,education_unknown,housing_no,housing_yes,loan_no,loan_yes,contact_cellular,contact_telephone,contact_unknown,month_apr,month_aug,month_dec,month_feb,month_jan,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,58,2143,5,261,1,-1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
1,44,29,5,151,1,-1,0,2,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
2,33,2,5,76,1,-1,0,3,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
3,47,1506,5,92,1,-1,0,4,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
4,33,1,5,198,1,-1,0,5,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1

In [12]:
column_list = bank_data.columns

In [15]:
column_list = [u'age', u'balance', u'day', u'duration', u'campaign', u'pdays',
               u'previous', u'risk', u'pdays_missing', u'job_admin.',
               u'job_blue-collar', u'job_entrepreneur', u'job_housemaid',
               u'job_management', u'job_retired', u'job_self-employed',
               u'job_services', u'job_student', u'job_technician', u'job_unemployed',
               u'job_unknown', u'marital_divorced', u'marital_married',
               u'marital_single', u'education_primary', u'education_secondary',
               u'education_tertiary', u'education_unknown', u'housing_no',
               u'housing_yes', u'loan_no', u'loan_yes', u'contact_cellular',
               u'contact_telephone', u'contact_unknown', u'month_apr', u'month_aug',
               u'month_dec', u'month_feb', u'month_jan', u'month_jul', u'month_jun',
               u'month_mar', u'month_may', u'month_nov', u'month_oct', u'month_sep',
               u'poutcome_failure', u'poutcome_other', u'poutcome_success',
               u'poutcome_unknown']

In [ ]:
from sklearn.cross_validation import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np

kf = KFold(bank_data.shape[0], n_folds=10, shuffle=True)

k_list = []
knn_accuracy_list = []
knn_accuracy_std_list = []

for i in range(1,21):
    cv_accuracy_list = []
    for train_index, test_index in kf:
        cv_train, cv_test = bank_data.ix[train_index], bank_data.ix[test_index]
        knn_model = KNeighborsClassifier(n_neighbors = i).fit(cv_train[column_list],cv_train['resp'])
        bank_data['knn'+str(i)] = knn_model.predict_proba(bank_data[column_list])
        predicted_class_name = knn_model.predict(cv_test[column_list])
        cv_accuracy_list.append(accuracy_score(cv_test['resp'], predicted_class_name))
        
    k_list.append(i)
    knn_accuracy_list.append(np.mean(cv_accuracy_list))
    knn_accuracy_std_list.append(np.std(cv_accuracy_list))
    print i, np.mean(cv_accuracy_list), np.std(cv_accuracy_list)

In [76]:
from sknn.mlp import Classifier, Layer

nn = Classifier(
    layers=[
        Layer("Rectifier", units=100),
        Layer("Softmax")],
    learning_rate=0.002,
    n_iter=1)

nn_model = nn.fit(bank_data[column_list], bank_data['resp'])

y_valid = nn_model.predict_proba(bank_data[column_list])
predicted_class_name = nn_model.predict(bank_data[column_list])

accuracy_score(bank_data['resp'], predicted_class_name)

[(45211, 2)]
[(45211, 2)]

0.67883922054367296

In [79]:
from sklearn.metrics import precision_recall_fscore_support

print precision_recall_fscore_support(bank_data['resp'], predicted_class_name, average='binary', pos_label=0)

(0.89732841143715203, 0.71850107710034572, 0.79801914088582249, None)

In [97]:
from sklearn.ensemble import RandomForestClassifier

rfc_model = RandomForestClassifier(n_estimators=100, max_depth=None, min_samples_leaf=10, n_jobs=-1, 
                                   random_state=1234, verbose=0).fit(bank_data[column_list],bank_data['resp'])
rfc_score = rfc_model.predict_proba(bank_data[column_list])
predicted_class_name = rfc_model.predict(bank_data[column_list])
print accuracy_score(bank_data['resp'], predicted_class_name)
print precision_recall_fscore_support(bank_data['resp'], predicted_class_name, average='binary', pos_label=1)
print precision_recall_fscore_support(bank_data['resp'], predicted_class_name, average='binary', pos_label=0)

0.921965893256
(0.84300740163615118, 0.40915106825486858, 0.5509164969450101, None)
(0.92671888190601259, 0.98990531536496162, 0.9572705471986046, None)

In [103]:
bank_data['RF_score']=rfc_model.predict_proba(bank_data[column_list])[:,1]

In [105]:
bank_data[['id','resp','RF_score']]

          id  resp  RF_score
0          1     0  0.005417
1          2     0  0.000695
2          3     0  0.005862
3          4     0  0.004717
4          5     0  0.017229
5          6     0  0.002683
6          7     0  0.016021
7          8     0  0.024215
8          9     0  0.001549
9         10     0  0.001976
10        11     0  0.006903
11        12     0  0.001805
12        13     0  0.056569
13        14     0  0.005901
14        15     0  0.003906
15        16     0  0.002124
16        17     0  0.005765
17        18     0  0.002759
18        19     0  0.014849
19        20     0  0.003624
20        21     0  0.007315
21        22     0  0.005389
22        23     0  0.006570
23        24     0  0.003792
24        25     0  0.004624
25        26     0  0.005001
26        27     0  0.005816
27        28     0  0.002497
28        29     0  0.002753
29        30     0  0.004445
...      ...   ...       ...
45181  45182     0  0.071070
45182  45183     1  0.780160
45183  45184     0  0.382032
45184  45185     0  0.446437
45185  45186     1  0.576190
45186  45187     0  0.254592
45187  45188     1  0.215735
45188  45189     1  0.548943
45189  45190     0  0.282591
45190  45191     1  0.727276
45191  45192     1  0.284185
45192  45193     1  0.315318
45193  45194     1  0.760931
45194  45195     0  0.057170
45195  45196     1  0.730546
45196  45197     1  0.489856
45197  45198     1  0.114814
45198  45199     0  0.207349
45199  45200     0  0.439732
45200  45201     1  0.582317
45201  45202     1  0.811867
45202  45203     1  0.175242
45203  45204     1  0.440516
45204  45205     1  0.407378
45205  45206     1  0.309039
45206  45207     1  0.518522
45207  45208     1  0.539643
45208  45209     1  0.675708
45209  45210     0  0.164139
45210  45211     0  0.339800

[45211 rows x 3 columns]

In [96]:
from sklearn.cross_validation import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np

kf = KFold(bank_data.shape[0], n_folds=10, shuffle=True)

for train_index, test_index in kf:
    cv_train, cv_test = bank_data.ix[train_index], bank_data.ix[test_index]
    
    rfc_model = RandomForestClassifier(n_estimators=100, max_depth=None, min_samples_leaf=10, n_jobs=-1, 
                                   random_state=1234, verbose=1).fit(cv_train[column_list],cv_train['resp'])
    
    rfc_score = rfc_model.predict_proba(cv_test[column_list])

    predicted_class_name = rfc_model.predict(cv_test[column_list])
    cv_accuracy_list.append(accuracy_score(cv_test['resp'], predicted_class_name))
    
print np.mean(cv_accuracy_list), np.std(cv_accuracy_list)

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    0.9s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    2.5s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    2.5s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    2.5s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    2.5s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    0.9s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    2.2s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    1.2s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    2.9s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    1.5s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    3.1s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    2.9s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    3.2s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.3s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    1.5s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    3.2s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished

0.90918192863 0.0102370636212